version: '3.1'
services:
  db:
    container_name: db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=bitly
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=users_service
      - MYSQL_PASSWORD=123
    volumes:
      - /mysql/datadir:/var/lib/mysql
      - ./mysql_dump/bitly.sql:/docker-entrypoint-initdb.d/bitly.sql
  node:
    image: node:14.5.0
    working_dir: /app/api
    command:
      - /bin/sh
      - '-c'
      - 'npm install && npm start'
    ports:
     - "8125:8125"
    depends_on:
     - db
    restart: on-failure
    environment:
     - DATABASE_HOST=db
    volumes:
     - ./src/api:/app/api
  pma:
    image: phpmyadmin:latest
    restart: on-failure
    environment:
      - PMA_HOST=db
      - PMA_USER=users_service
      - PMA_PASSWORD=123
      - MYSQL_ROOT_PASSWORD=1234
      - PMA_ARBITRARY=1
    ports:
      - "8080:80"